name: Build & Deploy to S3
on:
  push:
    # mainブランチのソースが改変されたら実行される
    branches: [main]
    paths:
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      CHANNEL_ID: C03HTB5869H # 通知を送りたいチャンネルのIDを指定する
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to S3
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: | #S3 バケットにデプロイ
          aws s3 rm s3://$S3_UPLOAD_BUCKET --recursive
          aws s3 cp dist s3://$S3_UPLOAD_BUCKET --recursive

      - name: Set COMMIT_MESSAGE
        run: echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": "Build & Deploy Success!!",
              "attachments": [
                {
                  "color": "00FF00",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "title": "Commit Message",
                      "value": "${{ env.COMMIT_MESSAGE }}",
                      "short": false
                    },
                    {
                      "title": "Staging URL",
                      "value": "<${{ secrets.STAGING_URL }}>",
                      "short": false
                    },
                    {
                      "title": "GitHub Actions URL",
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "short": false
                    },
                    { 
                      "title": "Compare URL",
                      "value": "${{ github.event.compare }}",
                      "short": false
                    }
                  ]
                }
              ]
            }

      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": "Build & Deploy Failure...",
              "attachments": [
                {
                  "color": "FF0000",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "title": "Commit Message",
                      "value": "${{ env.COMMIT_MESSAGE }}",
                      "short": false
                    },
                    {
                      "title": "GitHub Actions URL",
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "short": false
                    },
                    {
                      "title": "Compare URL",
                      "value": "${{ github.event.compare }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
