name: Playwright Tests
on:
  # S3 へのデプロイが完了したらE2Eテストを実行する
  workflow_run:
    workflows:
      - Build & Deploy to S3
    branches:
      - main
    types:
      - completed
  workflow_dispatch:
jobs:
  e2e_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # デプロイが成功していないと実施しない
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      CHANNEL_ID: C03HTB5869H # 通知を送りたいチャンネルのIDを指定する
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          STAGING_URL: ${{ secrets.STAGING_URL }}
        run: npm run e2e:all

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 5

      - name: Set COMMIT_MESSAGE
        run: echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": "E2E-test Success!!",
              "attachments": [
                {
                  "color": "00FF00",
                  "fields": [
                    {
                      "title": "GitHub Actions URL (with Artifacts)",
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "short": false
                    }
                  ]
                }
              ]
            }

      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": "E2E-test Failure...",
              "attachments": [
                {
                  "color": "FF0000",
                  "fields": [
                    {
                      "title": "GitHub Actions URL (with Artifacts)",
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "short": false
                    }
                  ]
                }
              ]
            }
