name: Slack chat.postMessage
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      CHANNEL_ID: C03HTB5869H # 通知を送りたいチャンネルのIDを指定する
    steps:
      - uses: actions/checkout@v2

      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ CHANNEL_ID }}
          payload: |
            {
              "text": "Build & Deploy Success!!",
              "attachments": [
                {
                  "id": 1,
                  "color": "00FF00",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "title": "GitHub Actions URL",
                      "short": false
                    },
                    {
                      "value": "${{ github.event.compare }}",
                      "title": "Compare URL",
                      "short": false
                    }
                  ]
                }
              ]
            }

      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ CHANNEL_ID }}
          payload: |
            {
              "text": "Build & Failure...",
              "attachments": [
                {
                  "id": 1,
                  "color": "00FF00",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "title": "GitHub Actions URL",
                      "short": false
                    },
                    {
                      "value": "${{ github.event.compare }}",
                      "title": "Compare URL",
                      "short": false
                    }
                  ]
                }
              ]
            }
