name: Slack chat.postMessage
on:
  push:
    paths:
      - ".github/workflows/slack-test.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Set COMMIT_MESSAGE
        run: echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Slack Notification on Success
        if: always() # success()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Process Success!!",
              "attachments": [
                {
                  "color": "good",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "title": "Commit Message",
                      "value": "${{ env.COMMIT_MESSAGE }}",
                      "short": false
                    },
                    {
                      "title": "GitHub Actions URL",
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "short": false
                    },
                    { 
                      "title": "Compare URL",
                      "value": "${{ github.event.compare }}",
                      "short": false
                    }
                  ]
                }
              ]
            }

      - name: Slack Notification on Failure
        if: always() # failure()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Process Failure...",
              "attachments": [
                {
                  "color": "danger",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "title": "Commit Message",
                      "value": "${{ env.COMMIT_MESSAGE }}",
                      "short": false
                    },
                    {
                      "value": "<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>",
                      "title": "GitHub Actions URL",
                      "short": false
                    },
                    {
                      "value": "${{ github.event.compare }}",
                      "title": "Compare URL",
                      "short": false
                    }
                  ]
                }
              ]
            }
