name: Slack chat.postMessage
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Set COMMIT_MESSAGE
        run: echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Process Success!!",
              "attachments": [
                {
                  "color": "00FF00",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "<${{ github.event.sender.avatar_url }}>",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Commit Message* \n ${{ env.COMMIT_MESSAGE }}"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*GitHub Actions URL* \n <${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Compare URL* \n <${{ github.event.compare }}>"
                      }
                    }
                  ]
                }
              ]
            }

      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Process Failure...",
              "attachments": [
                {
                  "color": "FF0000",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "<${{ github.event.sender.avatar_url }}>",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Commit Message* \n ${{ env.COMMIT_MESSAGE }}"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*GitHub Actions URL* \n <${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}>"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Compare URL* \n <${{ github.event.compare }}>"
                      }
                    }
                  ]
                }
              ]
            }
