name: Slack chat.postMessage
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      CHANNEL_ID: C03HTB5869H # 通知を送りたいチャンネルのIDを指定する
    steps:
      - uses: actions/checkout@v2

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": "Build & Deploy Success!!",
              "attachments": [
                {
                  "id": 1,
                  "color": "00FF00",
                  "fallback": "[no preview available]",
                  "author_name": "OECs2fujita",
                  "author_icon": "https://github.com/OECs2fujita.png",
                  "fields": [
                    {
                      "value": "<https://github.com/OECs2fujita/sandbox/actions/runs/2487204728>",
                      "title": "GitHub Actions URL",
                      "short": false
                    },
                    {
                      "value": "test",
                      "title": "Compare URL",
                      "short": false
                    }
                  ]
                }
              ],
              "blocks": [
                {
                  "type": "rich_text",
                  "block_id": "oUIu",
                  "elements": [
                    {
                      "type": "rich_text_section",
                      "elements": [
                        {
                          "type": "text",
                          "text": "Build & Deploy Success!!"
                        }
                      ]
                    }
                  ]
                }
              ]
            }

      - name: Send GitHub Action trigger data to Slack workflow2
        id: slack2
        uses: slackapi/slack-github-action@v1.19.0
        with:
          # 以下のように #チャンネル名も動作はしますが
          # チャンネル名が変更されると動かなくなるので
          # 実運用では C1QAUTY0M のような ID を使ってください
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": ":github: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":github: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
                    }
                  ]
                }
              ]
            }
